version: '3.5'
services:

  jdk8:
    image: goodow/jenkins-slave-jdk8
    build:
      context: jenkins-slave-jdk8
      args:
        http_proxy: http://proxy.cid.goodow.com:8080
        https_proxy: http://proxy.cid.goodow.com:8080

  go-dev:
    image: goodow/golang-development
    build:
      context: golang-development
      args:
        http_proxy: http://proxy.cid.goodow.com:8080
        https_proxy: http://proxy.cid.goodow.com:8080