version: '3.5'
services:

  jdk8:
    image: goodow/jenkins-slave-jdk8
    build:
      context: jenkins-slave-jdk8
      args:
        http_proxy: http://proxy.cid.goodow.com:8080
        https_proxy: http://proxy.cid.goodow.com:8080
  golang:
    image: goodow/jenkins-slave-golang
    build:
      context: jenkins-slave-golang
      args:
        http_proxy: http://proxy.cid.goodow.com:8080
        https_proxy: http://proxy.cid.goodow.com:8080