version: '3.5'
services:

  go:
    image: goodow/go-base
    build:
      context: node+typescript
      args:
        http_proxy: http://proxy.cid.goodow.com:8080
        https_proxy: http://proxy.cid.goodow.com:8080